[build-system]
requires = [
    "uv_build>=0.9.6,<0.10.0",
]
build-backend = "uv_build"

[tool.settings]
requires-python = ">=3.10"

[tool.uv]
dev-dependencies = [
    "pytest",
]

[tool.uv.workspace]
members = [
    "*",
]
exclude = [
    "__*",
    "*.egg-info",
    "build",
    "dist",
    "prpr",
]

[tool.uv.sources.scripts]
workspace = true
