[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
dev-dependencies = [
    "pytest",
]

[tool.uv.workspace]
members = [
    "*",
]
exclude = [
    "dev-local",
    "__*",
    "*.egg-info",
    "build",
    "dist",
    "prpr",
]

[tool.member-project]
project.requires-python = ">=3.12"
