[build-system]
requires = [
    "uv_build>=0.8.23,<0.9.0",
]
build-backend = "uv_build"

[project]
name = "reggie-tools"
version = "0.0.1+gbd680f4"
requires-python = ">=3.10"
dependencies = [
    "reggie-core",
    "databricks-sdk",
    "databricks-connect<=17.1",
    "requests",
    "urllib3",
    "pydantic",
]
