[project]
name = "reggie-tools"
version = "0.0.1+gb4edfd9"
requires-python = ">=3.10"
dependencies = [
    "reggie-core",
    "databricks-sdk",
    "databricks-connect<=17.1",
    "requests",
    "urllib3",
    "pydantic",
]
