[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "dbx-tools"
version = "0.0.1+g331acef"
requires-python = ">=3.12,<3.13"
dependencies = [
    "databricks-connect>=17.3,<18.0",
    "pydantic",
    "pyyaml",
    "dbx-core @ file://${PROJECT_ROOT}/../dbx-core",
]

[dependency-groups]
dev = ["wrapt>=2.0"]

[tool.uv.sources.dbx-core]
workspace = true
