[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "dbx-tools"
version = "0.0.1+gccf66c7"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dbx-runtime @ file://${PROJECT_ROOT}/../dbx-runtime",
    "pydantic",
    "dbx-core @ file://${PROJECT_ROOT}/../dbx-core",
]

[tool.uv.sources.dbx-core]
workspace = true

[tool.uv.sources.dbx-runtime]
workspace = true
