[project]
name = "generators-franchise"
version = "0.0.1+ga81da09"
requires-python = ">=3.10"
dependencies = [
    "reggie-core",
    "reggie-tools",
    "xhtml2pdf",
    "faker",
    "random-address",
    "beautifulsoup4",
    "jinja2",
    "markovify",
]
