[project]
name = "generators-franchise"
version = "0.0.1+g7f7caf4"
dependencies = [
    "reggie-core",
    "reggie-tools",
    "xhtml2pdf",
    "faker",
    "random-address",
    "beautifulsoup4",
    "jinja2",
    "markovify",
]
