[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "dbx-ai"
version = "0.0.1+g20a9a42"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dbx-tools @ file://${PROJECT_ROOT}/../dbx-tools",
    "pydantic_ai",
    "chromadb",
    "sentence-transformers",
]

[dependency-groups]
dev = ["textual", "google-auth", "google-auth-oauthlib", "emlx"]

[tool.uv.sources.dbx-tools]
workspace = true
