[project]
name = "reggie-concurio"
version = "0.0.1+gb745e06"
dependencies = [
    "reggie-core @ file://${PROJECT_ROOT}/../reggie-core",
    "diskcache",
    "fasteners",
]

[tool.uv.sources.reggie-core]
workspace = true

[build-system]
requires = [
    "uv_build>=0.9.6,<0.10.0",
]
build-backend = "uv_build"
