[project]
name = "reggie-concurio"
version = "0.0.1+gadf4496"
requires-python = ">=3.10"
dependencies = [
    "reggie-core",
    "diskcache",
    "fasteners",
]

[tool.uv.sources.reggie-core]
workspace = true
