[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "demo-iot"
version = "0.0.1+g767bd46"
requires-python = ">=3.10"
dependencies = [
    "reggie-tools @ file://${PROJECT_ROOT}/../reggie-tools",
    "uvicorn",
    "fastapi",
    "humanize"
]

[tool.uv.sources.reggie-tools]
workspace = true
