[project]
name = "scripts"
version = "0"
description = "Local build utilities"
dependencies = [
    "toml",
    "python-benedict[toml]",
    "tomlkit",
    "packaging",
]

[tool.uv]
managed = true
skip-build = true

[tool.uv_build]
package = false
