[build-system]
requires = [
    "uv_build>=0.8.23,<0.9.0",
]
build-backend = "uv_build"

[project]
name = "reggie-core"
version = "0.0.1+gd46f73c"
requires-python = ">=3.10"
dependencies = [
    "sitecustomize-entrypoints",
]

[project.entry-points.sitecustomize]
logs_auto_config = "reggie_core.logs:auto_config"

[project.optional-dependencies]
dev = [
    "pytest",
]
