[project]
name = "reggie-core"
version = "0.0.1+g67517ed"
requires-python = ">=3.10"
dependencies = [
    "sitecustomize-entrypoints",
]

[project.entry-points.sitecustomize]
logs_auto_config = "reggie_core.logs:auto_config"
