[project]
name = "reggie-core"
version = "0.0.1+gb745e06"
dependencies = [
    "sitecustomize-entrypoints",
]

[project.entry-points.sitecustomize]
logs_auto_config = "reggie_core.logs:auto_config"

[build-system]
requires = [
    "uv_build>=0.9.6,<0.10.0",
]
build-backend = "uv_build"
