[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "dbx-core"
version = "0.0.1+gf54493c"
requires-python = ">=3.12,<3.13"
dependencies = ["lfp-logging @ git+https://github.com/regbo/lfp-logging-py.git"]
