[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "dbx-core"
version = "0.0.1+gaa2c916"
requires-python = ">=3.12,<3.13"
depdendencies = [
    "lfp-logging @ git+https://github.com/regbo/lfp-logging-py.git",
]
