[project]
name = "reggie-app-runner"
version = "0.0.1+g67517ed"
dependencies = [
    "reggie-core",
    "reggie-tools",
    "dynaconf",
    "pyaml",
    "sh",
    "psutil",
    "requirements-parser",
    "giturlparse",
]
